---
# tasks file for ansible-graylogclient Redis SYSLOG

  ## Prior to 5.X .Add 'syslog' in RootLogger in logging.yml ##
- name: Syslog RootLogger (prior to 5.X)
  lineinfile:
    dest: "{{ graylogclient_elasticsearch_old_configuration_path }}"
    regexp: '^(rootLogger:(?!.*\bsyslog\b).*)$'
    line: '\1, syslog'
    backrefs: yes
  when: es_version|version_compare("5.0.0",'<')
  notify: Restart Elasticsearch

  ## Prior to 5.X .Add syslogblock in Appender, with  "content: |2"  to have the block correctly indented ##
- name: Syslog Block in Appender (prior to 5.X)
  blockinfile:
    dest: "{{ graylogclient_elasticsearch_old_configuration_path }}"
    marker: "  ### {mark} ANSIBLE MANAGED BLOCK ###  "
    insertafter: "appender:"
    content: |2
        syslog:
          type: syslog
          syslogHost: "{{ graylogclient_graylog_server_addr }}:{{ graylogclient_graylog_server_port }}"
          facility: "{{ graylogclient_elasticsearch_localname }}"
          layout:
            type: pattern
            conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %.10000m%n"
  when: es_version|version_compare("5.0.0",'<')
  notify: Restart Elasticsearch

  ## 5.X only
- name: Syslog block in Appender (5.X)
  blockinfile:
    dest: "{{ graylogclient_elasticsearch_configuration_path }}"
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: |
      #syslog
      rootLogger.appenderRef.syslog.ref = syslog
      appender.syslog.name = syslog
      appender.syslog.type = syslog
      appender.syslog.protocol = {{ graylogclient_protocol }}
      appender.syslog.host = {{ graylogclient_graylog_server_addr }}
      appender.syslog.port = {{ graylogclient_graylog_server_port }}
      appender.syslog.facility = {{ graylogclient_elasticsearch_localname }}
      appender.syslog.layout.type = PatternLayout
      appender.syslog.layout.pattern = "[%d{ISO8601}][%-5p][%-25c] %.10000m%n"
  when: es_version|version_compare("5.0.0",'>=')
  notify: Restart Elasticsearch
