---
- name: Update apache2.conf
  template:
    src="graylogclient_apache_conf.tpl"
    dest="/etc/apache2/apache2.conf"
    mode=0644

- name: delamerde
  command: "ls /etc/apache2/sites-available/"
  register: graylogclient_apache_vhost_files_list

- name: Update VHost conf
  blockinfile:
    dest: /etc/apache2/sites-available/{{ item }}
    insertbefore: "LogLevel warn"
#    insertafter: "CustomeLog"
    content: |
      CustomLog /var/log/apache2/putaindetamere.access.log combined
      SetEnvIfNoCase User-Agent "^$" lbreq
             CustomLog "| /bin/nc -u 192.168.229.133 12201" graylog2_access ENV=!lbreq
  with_items: graylogclient_apache_vhost_files_list.stdout_lines
  notify: Restart Apache

#  blockinfile:
#    dest: /var/www/html/index.html
#    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
#    content: |
#      <h1>Welcome to {{ansible_hostname}}</h1>
#      <p>Last updated on {{ansible_date_time.iso8601}}</p>

#  lineinfile: dest=/etc/apache2/sites-available/{{ item }} regexp="CustomLog" line="\t CustomLog \"| /bin/nc -u {{ graylogclient_graylog_server_addr }} 12201\" graylog2_access ENV=!lbreq\n"
