---
# handlers file for ansible-graylogclient

- name: Restart Rsyslog
  become: yes
  service:
    name=rsyslog
    state=restarted

- name: Restart nxlog
  become: yes
  service:
    name=nxlog
    state=restarted

### Handlers Elasticsearch ###
- name: Restart Elasticsearch
  become: yes
  service:
    name=elasticsearch
    state=restarted

### Handlers Cassandra ###
- name: Restart Cassandra
  become: yes
  service:
    name=cassandra
    state=restarted

### Handlers Apache ###
- name: Restart Apache
  become: yes
  service:
    name=apache2
    state=restarted

### Handlers Nginx ###
- name: Restart Nginx
  become: yes
  service:
    name=nginx
    state=restarted

### Handlers Karaf ###
- name: Restart Karaf
  become: yes
  service:
    name=karaf
    state=restarted
